export const customers = [
  {
    id: "CUS-1001",
    name: "Amara Dube",
    email: "amara.dube@example.com",
    phone: "+267 71 234 501",
    product: "Term Life",
    policies: 2,
    status: "Verified",
    initials: "AD",
    color: "green",
  },
  {
    id: "CUS-1002",
    name: "Thabo Molefe",
    email: "thabo.molefe@example.com",
    phone: "+267 72 345 612",
    product: "Family Funeral",
    policies: 1,
    status: "Verified",
    initials: "TM",
    color: "purple",
  },
  {
    id: "CUS-1003",
    name: "Naledi Kgosi",
    email: "naledi.kgosi@example.com",
    phone: "+267 73 456 723",
    product: "Care Cash",
    policies: 1,
    status: "Pending KYC",
    initials: "NK",
    color: "amber",
  },
  {
    id: "CUS-1004",
    name: "Kabelo Mokoena",
    email: "kabelo.mokoena@example.com",
    phone: "+267 74 567 834",
    product: "Whole of Life",
    policies: 3,
    status: "Verified",
    initials: "KM",
    color: "blue",
  },
  {
    id: "CUS-1005",
    name: "Lerato Ndlovu",
    email: "lerato.ndlovu@example.com",
    phone: "+267 75 678 945",
    product: "Term Life",
    policies: 1,
    status: "Verified",
    initials: "LN",
    color: "green",
  },
  {
    id: "CUS-1006",
    name: "Neo Modise",
    email: "neo.modise@example.com",
    phone: "+267 76 789 056",
    product: "Individual Credit",
    policies: 1,
    status: "Pending KYC",
    initials: "NM",
    color: "purple",
  },
];
export const initialApplications = [
  {
    id: "APP-2048",
    name: "Amara Dube",
    product: "Term Life",
    amount: 500000,
    premium: 420,
    status: "Under review",
    date: "28 Sep 2026",
  },
  {
    id: "APP-2047",
    name: "Thabo Molefe",
    product: "Family Funeral",
    amount: 50000,
    premium: 185,
    status: "Ready to issue",
    date: "28 Sep 2026",
  },
  {
    id: "APP-2046",
    name: "Naledi Kgosi",
    product: "Care Cash",
    amount: 1000,
    premium: 265,
    status: "Evidence needed",
    date: "27 Sep 2026",
  },
  {
    id: "APP-2045",
    name: "Lerato Ndlovu",
    product: "Term Life",
    amount: 350000,
    premium: 315,
    status: "Under review",
    date: "27 Sep 2026",
  },
  {
    id: "APP-2044",
    name: "Neo Modise",
    product: "Individual Credit",
    amount: 180000,
    premium: 210,
    status: "Draft",
    date: "26 Sep 2026",
  },
];
export const initialPolicies = [
  {
    id: "POL-10842",
    name: "Kabelo Mokoena",
    product: "Whole of Life",
    amount: 750000,
    premium: 680,
    status: "In force",
    date: "01 Jan 2026",
  },
  {
    id: "POL-10841",
    name: "Amara Dube",
    product: "Term Life",
    amount: 500000,
    premium: 420,
    status: "In force",
    date: "01 Mar 2026",
  },
  {
    id: "POL-10840",
    name: "Thabo Molefe",
    product: "Family Funeral",
    amount: 50000,
    premium: 185,
    status: "In force",
    date: "01 Apr 2026",
  },
  {
    id: "POL-10839",
    name: "Lerato Ndlovu",
    product: "Term Life",
    amount: 350000,
    premium: 315,
    status: "Grace period",
    date: "01 Feb 2026",
  },
  {
    id: "POL-10838",
    name: "Neo Modise",
    product: "Individual Credit",
    amount: 180000,
    premium: 210,
    status: "Lapsed",
    date: "01 Jun 2025",
  },
];
export const initialClaims = [
  {
    id: "CLM-0842",
    name: "Thabo Molefe",
    product: "Family Funeral",
    amount: 25000,
    status: "Assessment",
    date: "28 Sep 2026",
    type: "Funeral benefit",
  },
  {
    id: "CLM-0841",
    name: "Naledi Kgosi",
    product: "Care Cash",
    amount: 4500,
    status: "Evidence needed",
    date: "27 Sep 2026",
    type: "Hospital admission",
  },
  {
    id: "CLM-0840",
    name: "Kabelo Mokoena",
    product: "Whole of Life",
    amount: 6800,
    status: "Approved",
    date: "25 Sep 2026",
    type: "Scheduled benefit",
  },
  {
    id: "CLM-0839",
    name: "Amara Dube",
    product: "Term Life",
    amount: 4200,
    status: "Settled",
    date: "24 Sep 2026",
    type: "Scheduled benefit",
  },
];
export const products = [
  {
    name: "Term Life",
    icon: "ShieldCheck",
    color: "green",
    description: "Protection for the chapters that matter.",
    cover: "BWP 500,000",
    premium: "420",
    count: 4820,
  },
  {
    name: "Whole of Life",
    icon: "HeartHandshake",
    color: "purple",
    description: "Lifelong confidence. Lasting peace of mind.",
    cover: "BWP 750,000",
    premium: "680",
    count: 3160,
  },
  {
    name: "Family Funeral",
    icon: "Users",
    color: "amber",
    description: "A helping hand for the people you love.",
    cover: "BWP 50,000",
    premium: "185",
    count: 2950,
  },
  {
    name: "Care Cash",
    icon: "HeartPulse",
    color: "blue",
    description: "Everyday support during a hospital stay.",
    cover: "BWP 1,000 / day",
    premium: "265",
    count: 1640,
  },
  {
    name: "Individual Credit",
    icon: "Wallet",
    color: "purple",
    description: "Protect their future. Cover the balance.",
    cover: "BWP 180,000",
    premium: "210",
    count: 910,
  },
];
export const schemes = [
  {
    id: "SCH-001",
    name: "Okavango Holdings",
    sector: "Professional services",
    initials: "OH",
    members: 248,
    premium: 86400,
    renewal: "01 Jan 2027",
    color: "green",
  },
  {
    id: "SCH-002",
    name: "Kalahari Logistics",
    sector: "Transport & logistics",
    initials: "KL",
    members: 186,
    premium: 64200,
    renewal: "01 Feb 2027",
    color: "purple",
  },
  {
    id: "SCH-003",
    name: "Pula Community Bank",
    sector: "Financial services",
    initials: "PB",
    members: 324,
    premium: 112800,
    renewal: "01 Mar 2027",
    color: "blue",
  },
];
export const money = (value) => "BWP " + Number(value).toLocaleString("en-GB");
export const initials = (name) =>
  name
    .split(" ")
    .map((n) => n[0])
    .slice(0, 2)
    .join("");
